# Site settings
title: Icewyrm Hoard
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A place for information related to Icewyrm Games, an indie
  development studio in Anchorage, Alaska.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://IcewyrmGames.github.io" # the base hostname & protocol for your site
twitter_username: IcewyrmGames
github_username:  IcewyrmGames

author:
  name: Justin Bool
  email: booljayj@gmail.com
  github: booljayj

permalink: /:year/:month/:day/:title/
paginate: 10

# Build settings
markdown: redcarpet

collections:
  research:
    output: true
    permalink: /:collection/:title/
  examples:
    output: true
    permalink: /:collection/:title/