# Site settings
title: Icewyrm Games Databank
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A place for information related to Icewyrm Games, an indie
  development studio in Anchorage, Alaska.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://IcewyrmGames.github.io" # the base hostname & protocol for your site
twitter_username: IcewyrmGames
github_username:  IcewyrmGames

author:
  name: Justin Bool
  email: booljayj@gmail.com
  github: booljayj

# Build settings
markdown: kramdown

collections:
  articles:
    output: true
  research:
    output: true
  examples:
    output: true
